package:
  name: ccphylo
  version: 0.8.3

source:
  url: https://bitbucket.org/genomicepidemiology/ccphylo/get/0.8.3.tar.gz

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - ccphylo -h | grep CCPhylo >/dev/null

about:
  home: https://bitbucket.org/genomicepidemiology/ccphylo
  summary: 'CCPhylo enables phylogenetic analysis of samples based on overlaps between nucleotide created by e.g. KMA. Input file(s) may be given as non-option arguments succeding all options.'
  license: Apache-2.0
extra:
  identifiers:
    - doi:10.1093/bioinformatics/btac774
    - doi:10.1093/biomethods/bpab008